// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mymqttmessages.proto

package com.example.harald.runwithme2.mymqttmessages;

public final class ProtobufMessages {
  private ProtobufMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RunMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mymqttmessages.RunMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 source = 1;</code>
     */
    boolean hasSource();
    /**
     * <code>required uint32 source = 1;</code>
     */
    int getSource();

    /**
     * <code>optional .mymqttmessages.PathItem pathItem = 101;</code>
     */
    boolean hasPathItem();
    /**
     * <code>optional .mymqttmessages.PathItem pathItem = 101;</code>
     */
    com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem getPathItem();
    /**
     * <code>optional .mymqttmessages.PathItem pathItem = 101;</code>
     */
    com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemOrBuilder getPathItemOrBuilder();

    public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage.MsgtypeCase getMsgtypeCase();
  }
  /**
   * Protobuf type {@code mymqttmessages.RunMessage}
   */
  public  static final class RunMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mymqttmessages.RunMessage)
      RunMessageOrBuilder {
    // Use RunMessage.newBuilder() to construct.
    private RunMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RunMessage() {
      source_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RunMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              source_ = input.readUInt32();
              break;
            }
            case 810: {
              com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem.Builder subBuilder = null;
              if (msgtypeCase_ == 101) {
                subBuilder = ((com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem) msgtype_).toBuilder();
              }
              msgtype_ =
                  input.readMessage(com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem) msgtype_);
                msgtype_ = subBuilder.buildPartial();
              }
              msgtypeCase_ = 101;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_RunMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_RunMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage.class, com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage.Builder.class);
    }

    private int bitField0_;
    private int msgtypeCase_ = 0;
    private java.lang.Object msgtype_;
    public enum MsgtypeCase
        implements com.google.protobuf.Internal.EnumLite {
      PATHITEM(101),
      MSGTYPE_NOT_SET(0);
      private final int value;
      private MsgtypeCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MsgtypeCase valueOf(int value) {
        return forNumber(value);
      }

      public static MsgtypeCase forNumber(int value) {
        switch (value) {
          case 101: return PATHITEM;
          case 0: return MSGTYPE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public MsgtypeCase
    getMsgtypeCase() {
      return MsgtypeCase.forNumber(
          msgtypeCase_);
    }

    public static final int SOURCE_FIELD_NUMBER = 1;
    private int source_;
    /**
     * <code>required uint32 source = 1;</code>
     */
    public boolean hasSource() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 source = 1;</code>
     */
    public int getSource() {
      return source_;
    }

    public static final int PATHITEM_FIELD_NUMBER = 101;
    /**
     * <code>optional .mymqttmessages.PathItem pathItem = 101;</code>
     */
    public boolean hasPathItem() {
      return msgtypeCase_ == 101;
    }
    /**
     * <code>optional .mymqttmessages.PathItem pathItem = 101;</code>
     */
    public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem getPathItem() {
      if (msgtypeCase_ == 101) {
         return (com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem) msgtype_;
      }
      return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem.getDefaultInstance();
    }
    /**
     * <code>optional .mymqttmessages.PathItem pathItem = 101;</code>
     */
    public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemOrBuilder getPathItemOrBuilder() {
      if (msgtypeCase_ == 101) {
         return (com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem) msgtype_;
      }
      return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSource()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasPathItem()) {
        if (!getPathItem().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, source_);
      }
      if (msgtypeCase_ == 101) {
        output.writeMessage(101, (com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem) msgtype_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, source_);
      }
      if (msgtypeCase_ == 101) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(101, (com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem) msgtype_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage)) {
        return super.equals(obj);
      }
      com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage other = (com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage) obj;

      boolean result = true;
      result = result && (hasSource() == other.hasSource());
      if (hasSource()) {
        result = result && (getSource()
            == other.getSource());
      }
      result = result && getMsgtypeCase().equals(
          other.getMsgtypeCase());
      if (!result) return false;
      switch (msgtypeCase_) {
        case 101:
          result = result && getPathItem()
              .equals(other.getPathItem());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSource()) {
        hash = (37 * hash) + SOURCE_FIELD_NUMBER;
        hash = (53 * hash) + getSource();
      }
      switch (msgtypeCase_) {
        case 101:
          hash = (37 * hash) + PATHITEM_FIELD_NUMBER;
          hash = (53 * hash) + getPathItem().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data.array());
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data.array(), extensionRegistry);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mymqttmessages.RunMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mymqttmessages.RunMessage)
        com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_RunMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_RunMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage.class, com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage.Builder.class);
      }

      // Construct using com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        source_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        msgtypeCase_ = 0;
        msgtype_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_RunMessage_descriptor;
      }

      public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage getDefaultInstanceForType() {
        return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage.getDefaultInstance();
      }

      public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage build() {
        com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage buildPartial() {
        com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage result = new com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.source_ = source_;
        if (msgtypeCase_ == 101) {
          if (pathItemBuilder_ == null) {
            result.msgtype_ = msgtype_;
          } else {
            result.msgtype_ = pathItemBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.msgtypeCase_ = msgtypeCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage) {
          return mergeFrom((com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage other) {
        if (other == com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage.getDefaultInstance()) return this;
        if (other.hasSource()) {
          setSource(other.getSource());
        }
        switch (other.getMsgtypeCase()) {
          case PATHITEM: {
            mergePathItem(other.getPathItem());
            break;
          }
          case MSGTYPE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSource()) {
          return false;
        }
        if (hasPathItem()) {
          if (!getPathItem().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int msgtypeCase_ = 0;
      private java.lang.Object msgtype_;
      public MsgtypeCase
          getMsgtypeCase() {
        return MsgtypeCase.forNumber(
            msgtypeCase_);
      }

      public Builder clearMsgtype() {
        msgtypeCase_ = 0;
        msgtype_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private int source_ ;
      /**
       * <code>required uint32 source = 1;</code>
       */
      public boolean hasSource() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 source = 1;</code>
       */
      public int getSource() {
        return source_;
      }
      /**
       * <code>required uint32 source = 1;</code>
       */
      public Builder setSource(int value) {
        bitField0_ |= 0x00000001;
        source_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 source = 1;</code>
       */
      public Builder clearSource() {
        bitField0_ = (bitField0_ & ~0x00000001);
        source_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem, com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem.Builder, com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemOrBuilder> pathItemBuilder_;
      /**
       * <code>optional .mymqttmessages.PathItem pathItem = 101;</code>
       */
      public boolean hasPathItem() {
        return msgtypeCase_ == 101;
      }
      /**
       * <code>optional .mymqttmessages.PathItem pathItem = 101;</code>
       */
      public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem getPathItem() {
        if (pathItemBuilder_ == null) {
          if (msgtypeCase_ == 101) {
            return (com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem) msgtype_;
          }
          return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem.getDefaultInstance();
        } else {
          if (msgtypeCase_ == 101) {
            return pathItemBuilder_.getMessage();
          }
          return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem.getDefaultInstance();
        }
      }
      /**
       * <code>optional .mymqttmessages.PathItem pathItem = 101;</code>
       */
      public Builder setPathItem(com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem value) {
        if (pathItemBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msgtype_ = value;
          onChanged();
        } else {
          pathItemBuilder_.setMessage(value);
        }
        msgtypeCase_ = 101;
        return this;
      }
      /**
       * <code>optional .mymqttmessages.PathItem pathItem = 101;</code>
       */
      public Builder setPathItem(
          com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem.Builder builderForValue) {
        if (pathItemBuilder_ == null) {
          msgtype_ = builderForValue.build();
          onChanged();
        } else {
          pathItemBuilder_.setMessage(builderForValue.build());
        }
        msgtypeCase_ = 101;
        return this;
      }
      /**
       * <code>optional .mymqttmessages.PathItem pathItem = 101;</code>
       */
      public Builder mergePathItem(com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem value) {
        if (pathItemBuilder_ == null) {
          if (msgtypeCase_ == 101 &&
              msgtype_ != com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem.getDefaultInstance()) {
            msgtype_ = com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem.newBuilder((com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem) msgtype_)
                .mergeFrom(value).buildPartial();
          } else {
            msgtype_ = value;
          }
          onChanged();
        } else {
          if (msgtypeCase_ == 101) {
            pathItemBuilder_.mergeFrom(value);
          }
          pathItemBuilder_.setMessage(value);
        }
        msgtypeCase_ = 101;
        return this;
      }
      /**
       * <code>optional .mymqttmessages.PathItem pathItem = 101;</code>
       */
      public Builder clearPathItem() {
        if (pathItemBuilder_ == null) {
          if (msgtypeCase_ == 101) {
            msgtypeCase_ = 0;
            msgtype_ = null;
            onChanged();
          }
        } else {
          if (msgtypeCase_ == 101) {
            msgtypeCase_ = 0;
            msgtype_ = null;
          }
          pathItemBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .mymqttmessages.PathItem pathItem = 101;</code>
       */
      public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem.Builder getPathItemBuilder() {
        return getPathItemFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .mymqttmessages.PathItem pathItem = 101;</code>
       */
      public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemOrBuilder getPathItemOrBuilder() {
        if ((msgtypeCase_ == 101) && (pathItemBuilder_ != null)) {
          return pathItemBuilder_.getMessageOrBuilder();
        } else {
          if (msgtypeCase_ == 101) {
            return (com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem) msgtype_;
          }
          return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem.getDefaultInstance();
        }
      }
      /**
       * <code>optional .mymqttmessages.PathItem pathItem = 101;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem, com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem.Builder, com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemOrBuilder> 
          getPathItemFieldBuilder() {
        if (pathItemBuilder_ == null) {
          if (!(msgtypeCase_ == 101)) {
            msgtype_ = com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem.getDefaultInstance();
          }
          pathItemBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem, com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem.Builder, com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemOrBuilder>(
                  (com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem) msgtype_,
                  getParentForChildren(),
                  isClean());
          msgtype_ = null;
        }
        msgtypeCase_ = 101;
        onChanged();;
        return pathItemBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mymqttmessages.RunMessage)
    }

    // @@protoc_insertion_point(class_scope:mymqttmessages.RunMessage)
    private static final com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage();
    }

    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<RunMessage>
        PARSER = new com.google.protobuf.AbstractParser<RunMessage>() {
      public RunMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RunMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RunMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RunMessage> getParserForType() {
      return PARSER;
    }

    public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.RunMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PathItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mymqttmessages.PathItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required double latitude = 1;</code>
     */
    boolean hasLatitude();
    /**
     * <code>required double latitude = 1;</code>
     */
    double getLatitude();

    /**
     * <code>required double longitude = 2;</code>
     */
    boolean hasLongitude();
    /**
     * <code>required double longitude = 2;</code>
     */
    double getLongitude();

    /**
     * <code>required uint64 time = 3;</code>
     */
    boolean hasTime();
    /**
     * <code>required uint64 time = 3;</code>
     */
    long getTime();

    /**
     * <code>required double distance = 4;</code>
     */
    boolean hasDistance();
    /**
     * <code>required double distance = 4;</code>
     */
    double getDistance();

    /**
     * <code>required double speed = 5;</code>
     */
    boolean hasSpeed();
    /**
     * <code>required double speed = 5;</code>
     */
    double getSpeed();

    /**
     * <code>required uint32 steps = 6;</code>
     */
    boolean hasSteps();
    /**
     * <code>required uint32 steps = 6;</code>
     */
    int getSteps();
  }
  /**
   * Protobuf type {@code mymqttmessages.PathItem}
   */
  public  static final class PathItem extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mymqttmessages.PathItem)
      PathItemOrBuilder {
    // Use PathItem.newBuilder() to construct.
    private PathItem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PathItem() {
      latitude_ = 0D;
      longitude_ = 0D;
      time_ = 0L;
      distance_ = 0D;
      speed_ = 0D;
      steps_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PathItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              latitude_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              longitude_ = input.readDouble();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              time_ = input.readUInt64();
              break;
            }
            case 33: {
              bitField0_ |= 0x00000008;
              distance_ = input.readDouble();
              break;
            }
            case 41: {
              bitField0_ |= 0x00000010;
              speed_ = input.readDouble();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              steps_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_PathItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_PathItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem.class, com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem.Builder.class);
    }

    private int bitField0_;
    public static final int LATITUDE_FIELD_NUMBER = 1;
    private double latitude_;
    /**
     * <code>required double latitude = 1;</code>
     */
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required double latitude = 1;</code>
     */
    public double getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 2;
    private double longitude_;
    /**
     * <code>required double longitude = 2;</code>
     */
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double longitude = 2;</code>
     */
    public double getLongitude() {
      return longitude_;
    }

    public static final int TIME_FIELD_NUMBER = 3;
    private long time_;
    /**
     * <code>required uint64 time = 3;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint64 time = 3;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int DISTANCE_FIELD_NUMBER = 4;
    private double distance_;
    /**
     * <code>required double distance = 4;</code>
     */
    public boolean hasDistance() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required double distance = 4;</code>
     */
    public double getDistance() {
      return distance_;
    }

    public static final int SPEED_FIELD_NUMBER = 5;
    private double speed_;
    /**
     * <code>required double speed = 5;</code>
     */
    public boolean hasSpeed() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required double speed = 5;</code>
     */
    public double getSpeed() {
      return speed_;
    }

    public static final int STEPS_FIELD_NUMBER = 6;
    private int steps_;
    /**
     * <code>required uint32 steps = 6;</code>
     */
    public boolean hasSteps() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required uint32 steps = 6;</code>
     */
    public int getSteps() {
      return steps_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasLatitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLongitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDistance()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSpeed()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSteps()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, latitude_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, longitude_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(3, time_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeDouble(4, distance_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeDouble(5, speed_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeUInt32(6, steps_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, latitude_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, longitude_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, time_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, distance_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(5, speed_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, steps_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem)) {
        return super.equals(obj);
      }
      com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem other = (com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem) obj;

      boolean result = true;
      result = result && (hasLatitude() == other.hasLatitude());
      if (hasLatitude()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getLatitude())
            == java.lang.Double.doubleToLongBits(
                other.getLatitude()));
      }
      result = result && (hasLongitude() == other.hasLongitude());
      if (hasLongitude()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getLongitude())
            == java.lang.Double.doubleToLongBits(
                other.getLongitude()));
      }
      result = result && (hasTime() == other.hasTime());
      if (hasTime()) {
        result = result && (getTime()
            == other.getTime());
      }
      result = result && (hasDistance() == other.hasDistance());
      if (hasDistance()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getDistance())
            == java.lang.Double.doubleToLongBits(
                other.getDistance()));
      }
      result = result && (hasSpeed() == other.hasSpeed());
      if (hasSpeed()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getSpeed())
            == java.lang.Double.doubleToLongBits(
                other.getSpeed()));
      }
      result = result && (hasSteps() == other.hasSteps());
      if (hasSteps()) {
        result = result && (getSteps()
            == other.getSteps());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasLatitude()) {
        hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getLatitude()));
      }
      if (hasLongitude()) {
        hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getLongitude()));
      }
      if (hasTime()) {
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTime());
      }
      if (hasDistance()) {
        hash = (37 * hash) + DISTANCE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getDistance()));
      }
      if (hasSpeed()) {
        hash = (37 * hash) + SPEED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getSpeed()));
      }
      if (hasSteps()) {
        hash = (37 * hash) + STEPS_FIELD_NUMBER;
        hash = (53 * hash) + getSteps();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data.array());
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data.array(), extensionRegistry);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mymqttmessages.PathItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mymqttmessages.PathItem)
        com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_PathItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_PathItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem.class, com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem.Builder.class);
      }

      // Construct using com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        latitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        longitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        time_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        distance_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000008);
        speed_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000010);
        steps_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_PathItem_descriptor;
      }

      public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem getDefaultInstanceForType() {
        return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem.getDefaultInstance();
      }

      public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem build() {
        com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem buildPartial() {
        com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem result = new com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.latitude_ = latitude_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.longitude_ = longitude_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.distance_ = distance_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.speed_ = speed_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.steps_ = steps_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem) {
          return mergeFrom((com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem other) {
        if (other == com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem.getDefaultInstance()) return this;
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasDistance()) {
          setDistance(other.getDistance());
        }
        if (other.hasSpeed()) {
          setSpeed(other.getSpeed());
        }
        if (other.hasSteps()) {
          setSteps(other.getSteps());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLatitude()) {
          return false;
        }
        if (!hasLongitude()) {
          return false;
        }
        if (!hasTime()) {
          return false;
        }
        if (!hasDistance()) {
          return false;
        }
        if (!hasSpeed()) {
          return false;
        }
        if (!hasSteps()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private double latitude_ ;
      /**
       * <code>required double latitude = 1;</code>
       */
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required double latitude = 1;</code>
       */
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>required double latitude = 1;</code>
       */
      public Builder setLatitude(double value) {
        bitField0_ |= 0x00000001;
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double latitude = 1;</code>
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000001);
        latitude_ = 0D;
        onChanged();
        return this;
      }

      private double longitude_ ;
      /**
       * <code>required double longitude = 2;</code>
       */
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double longitude = 2;</code>
       */
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>required double longitude = 2;</code>
       */
      public Builder setLongitude(double value) {
        bitField0_ |= 0x00000002;
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double longitude = 2;</code>
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000002);
        longitude_ = 0D;
        onChanged();
        return this;
      }

      private long time_ ;
      /**
       * <code>required uint64 time = 3;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required uint64 time = 3;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>required uint64 time = 3;</code>
       */
      public Builder setTime(long value) {
        bitField0_ |= 0x00000004;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 time = 3;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000004);
        time_ = 0L;
        onChanged();
        return this;
      }

      private double distance_ ;
      /**
       * <code>required double distance = 4;</code>
       */
      public boolean hasDistance() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required double distance = 4;</code>
       */
      public double getDistance() {
        return distance_;
      }
      /**
       * <code>required double distance = 4;</code>
       */
      public Builder setDistance(double value) {
        bitField0_ |= 0x00000008;
        distance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double distance = 4;</code>
       */
      public Builder clearDistance() {
        bitField0_ = (bitField0_ & ~0x00000008);
        distance_ = 0D;
        onChanged();
        return this;
      }

      private double speed_ ;
      /**
       * <code>required double speed = 5;</code>
       */
      public boolean hasSpeed() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required double speed = 5;</code>
       */
      public double getSpeed() {
        return speed_;
      }
      /**
       * <code>required double speed = 5;</code>
       */
      public Builder setSpeed(double value) {
        bitField0_ |= 0x00000010;
        speed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double speed = 5;</code>
       */
      public Builder clearSpeed() {
        bitField0_ = (bitField0_ & ~0x00000010);
        speed_ = 0D;
        onChanged();
        return this;
      }

      private int steps_ ;
      /**
       * <code>required uint32 steps = 6;</code>
       */
      public boolean hasSteps() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required uint32 steps = 6;</code>
       */
      public int getSteps() {
        return steps_;
      }
      /**
       * <code>required uint32 steps = 6;</code>
       */
      public Builder setSteps(int value) {
        bitField0_ |= 0x00000020;
        steps_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 steps = 6;</code>
       */
      public Builder clearSteps() {
        bitField0_ = (bitField0_ & ~0x00000020);
        steps_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mymqttmessages.PathItem)
    }

    // @@protoc_insertion_point(class_scope:mymqttmessages.PathItem)
    private static final com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem();
    }

    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<PathItem>
        PARSER = new com.google.protobuf.AbstractParser<PathItem>() {
      public PathItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PathItem(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PathItem> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PathItem> getParserForType() {
      return PARSER;
    }

    public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItem getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mymqttmessages_RunMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mymqttmessages_RunMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mymqttmessages_PathItem_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mymqttmessages_PathItem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024mymqttmessages.proto\022\016mymqttmessages\"U" +
      "\n\nRunMessage\022\016\n\006source\030\001 \002(\r\022,\n\010pathItem" +
      "\030e \001(\0132\030.mymqttmessages.PathItemH\000B\t\n\007ms" +
      "gtype\"m\n\010PathItem\022\020\n\010latitude\030\001 \002(\001\022\021\n\tl" +
      "ongitude\030\002 \002(\001\022\014\n\004time\030\003 \002(\004\022\020\n\010distance" +
      "\030\004 \002(\001\022\r\n\005speed\030\005 \002(\001\022\r\n\005steps\030\006 \002(\rB@\n," +
      "com.example.harald.runwithme2.mymqttmess" +
      "agesB\020ProtobufMessages"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_mymqttmessages_RunMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mymqttmessages_RunMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mymqttmessages_RunMessage_descriptor,
        new java.lang.String[] { "Source", "PathItem", "Msgtype", });
    internal_static_mymqttmessages_PathItem_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mymqttmessages_PathItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mymqttmessages_PathItem_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", "Time", "Distance", "Speed", "Steps", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
