// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mymqttmessages.proto

package com.example.harald.runwithme2.mymqttmessages;

public final class ProtobufMessages {
  private ProtobufMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PathItemMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mymqttmessages.PathItemMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint32 source = 1;</code>
     */
    boolean hasSource();
    /**
     * <code>required uint32 source = 1;</code>
     */
    int getSource();

    /**
     * <code>optional .mymqttmessages.GPSMessage gps = 101;</code>
     */
    boolean hasGps();
    /**
     * <code>optional .mymqttmessages.GPSMessage gps = 101;</code>
     */
    com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage getGps();
    /**
     * <code>optional .mymqttmessages.GPSMessage gps = 101;</code>
     */
    com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessageOrBuilder getGpsOrBuilder();

    /**
     * <code>optional .mymqttmessages.MetaValues meta = 102;</code>
     */
    boolean hasMeta();
    /**
     * <code>optional .mymqttmessages.MetaValues meta = 102;</code>
     */
    com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues getMeta();
    /**
     * <code>optional .mymqttmessages.MetaValues meta = 102;</code>
     */
    com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValuesOrBuilder getMetaOrBuilder();

    com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage.MsgtypeCase getMsgtypeCase();
  }
  /**
   * Protobuf type {@code mymqttmessages.PathItemMessage}
   */
  public  static final class PathItemMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mymqttmessages.PathItemMessage)
      PathItemMessageOrBuilder {
    // Use PathItemMessage.newBuilder() to construct.
    private PathItemMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PathItemMessage() {
      source_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PathItemMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              source_ = input.readUInt32();
              break;
            }
            case 810: {
              com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage.Builder subBuilder = null;
              if (msgtypeCase_ == 101) {
                subBuilder = ((com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage) msgtype_).toBuilder();
              }
              msgtype_ =
                  input.readMessage(com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage) msgtype_);
                msgtype_ = subBuilder.buildPartial();
              }
              msgtypeCase_ = 101;
              break;
            }
            case 818: {
              com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues.Builder subBuilder = null;
              if (msgtypeCase_ == 102) {
                subBuilder = ((com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues) msgtype_).toBuilder();
              }
              msgtype_ =
                  input.readMessage(com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues) msgtype_);
                msgtype_ = subBuilder.buildPartial();
              }
              msgtypeCase_ = 102;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_PathItemMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_PathItemMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage.class, com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage.Builder.class);
    }

    private int bitField0_;
    private int msgtypeCase_ = 0;
    private java.lang.Object msgtype_;
    public enum MsgtypeCase
        implements com.google.protobuf.Internal.EnumLite {
      GPS(101),
      META(102),
      MSGTYPE_NOT_SET(0);
      private final int value;
      MsgtypeCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static MsgtypeCase valueOf(int value) {
        return forNumber(value);
      }

      public static MsgtypeCase forNumber(int value) {
        switch (value) {
          case 101: return GPS;
          case 102: return META;
          case 0: return MSGTYPE_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    }

    public MsgtypeCase
    getMsgtypeCase() {
      return MsgtypeCase.forNumber(
          msgtypeCase_);
    }

    public static final int SOURCE_FIELD_NUMBER = 1;
    private int source_;
    /**
     * <code>required uint32 source = 1;</code>
     */
    public boolean hasSource() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint32 source = 1;</code>
     */
    public int getSource() {
      return source_;
    }

    public static final int GPS_FIELD_NUMBER = 101;
    /**
     * <code>optional .mymqttmessages.GPSMessage gps = 101;</code>
     */
    public boolean hasGps() {
      return msgtypeCase_ == 101;
    }
    /**
     * <code>optional .mymqttmessages.GPSMessage gps = 101;</code>
     */
    public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage getGps() {
      if (msgtypeCase_ == 101) {
         return (com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage) msgtype_;
      }
      return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage.getDefaultInstance();
    }
    /**
     * <code>optional .mymqttmessages.GPSMessage gps = 101;</code>
     */
    public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessageOrBuilder getGpsOrBuilder() {
      if (msgtypeCase_ == 101) {
         return (com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage) msgtype_;
      }
      return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage.getDefaultInstance();
    }

    public static final int META_FIELD_NUMBER = 102;
    /**
     * <code>optional .mymqttmessages.MetaValues meta = 102;</code>
     */
    public boolean hasMeta() {
      return msgtypeCase_ == 102;
    }
    /**
     * <code>optional .mymqttmessages.MetaValues meta = 102;</code>
     */
    public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues getMeta() {
      if (msgtypeCase_ == 102) {
         return (com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues) msgtype_;
      }
      return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues.getDefaultInstance();
    }
    /**
     * <code>optional .mymqttmessages.MetaValues meta = 102;</code>
     */
    public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValuesOrBuilder getMetaOrBuilder() {
      if (msgtypeCase_ == 102) {
         return (com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues) msgtype_;
      }
      return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSource()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasGps()) {
        if (!getGps().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasMeta()) {
        if (!getMeta().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, source_);
      }
      if (msgtypeCase_ == 101) {
        output.writeMessage(101, (com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage) msgtype_);
      }
      if (msgtypeCase_ == 102) {
        output.writeMessage(102, (com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues) msgtype_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, source_);
      }
      if (msgtypeCase_ == 101) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(101, (com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage) msgtype_);
      }
      if (msgtypeCase_ == 102) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(102, (com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues) msgtype_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage)) {
        return super.equals(obj);
      }
      com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage other = (com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage) obj;

      boolean result = true;
      result = result && (hasSource() == other.hasSource());
      if (hasSource()) {
        result = result && (getSource()
            == other.getSource());
      }
      result = result && getMsgtypeCase().equals(
          other.getMsgtypeCase());
      if (!result) return false;
      switch (msgtypeCase_) {
        case 101:
          result = result && getGps()
              .equals(other.getGps());
          break;
        case 102:
          result = result && getMeta()
              .equals(other.getMeta());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSource()) {
        hash = (37 * hash) + SOURCE_FIELD_NUMBER;
        hash = (53 * hash) + getSource();
      }
      switch (msgtypeCase_) {
        case 101:
          hash = (37 * hash) + GPS_FIELD_NUMBER;
          hash = (53 * hash) + getGps().hashCode();
          break;
        case 102:
          hash = (37 * hash) + META_FIELD_NUMBER;
          hash = (53 * hash) + getMeta().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data.array());
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data.array(), extensionRegistry);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mymqttmessages.PathItemMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mymqttmessages.PathItemMessage)
        com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_PathItemMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_PathItemMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage.class, com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage.Builder.class);
      }

      // Construct using com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        source_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        msgtypeCase_ = 0;
        msgtype_ = null;
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_PathItemMessage_descriptor;
      }

      public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage getDefaultInstanceForType() {
        return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage.getDefaultInstance();
      }

      public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage build() {
        com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage buildPartial() {
        com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage result = new com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.source_ = source_;
        if (msgtypeCase_ == 101) {
          if (gpsBuilder_ == null) {
            result.msgtype_ = msgtype_;
          } else {
            result.msgtype_ = gpsBuilder_.build();
          }
        }
        if (msgtypeCase_ == 102) {
          if (metaBuilder_ == null) {
            result.msgtype_ = msgtype_;
          } else {
            result.msgtype_ = metaBuilder_.build();
          }
        }
        result.bitField0_ = to_bitField0_;
        result.msgtypeCase_ = msgtypeCase_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage) {
          return mergeFrom((com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage other) {
        if (other == com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage.getDefaultInstance()) return this;
        if (other.hasSource()) {
          setSource(other.getSource());
        }
        switch (other.getMsgtypeCase()) {
          case GPS: {
            mergeGps(other.getGps());
            break;
          }
          case META: {
            mergeMeta(other.getMeta());
            break;
          }
          case MSGTYPE_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasSource()) {
          return false;
        }
        if (hasGps()) {
          if (!getGps().isInitialized()) {
            return false;
          }
        }
        if (hasMeta()) {
          if (!getMeta().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int msgtypeCase_ = 0;
      private java.lang.Object msgtype_;
      public MsgtypeCase
          getMsgtypeCase() {
        return MsgtypeCase.forNumber(
            msgtypeCase_);
      }

      public Builder clearMsgtype() {
        msgtypeCase_ = 0;
        msgtype_ = null;
        onChanged();
        return this;
      }

      private int bitField0_;

      private int source_ ;
      /**
       * <code>required uint32 source = 1;</code>
       */
      public boolean hasSource() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint32 source = 1;</code>
       */
      public int getSource() {
        return source_;
      }
      /**
       * <code>required uint32 source = 1;</code>
       */
      public Builder setSource(int value) {
        bitField0_ |= 0x00000001;
        source_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 source = 1;</code>
       */
      public Builder clearSource() {
        bitField0_ = (bitField0_ & ~0x00000001);
        source_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage, com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage.Builder, com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessageOrBuilder> gpsBuilder_;
      /**
       * <code>optional .mymqttmessages.GPSMessage gps = 101;</code>
       */
      public boolean hasGps() {
        return msgtypeCase_ == 101;
      }
      /**
       * <code>optional .mymqttmessages.GPSMessage gps = 101;</code>
       */
      public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage getGps() {
        if (gpsBuilder_ == null) {
          if (msgtypeCase_ == 101) {
            return (com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage) msgtype_;
          }
          return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage.getDefaultInstance();
        } else {
          if (msgtypeCase_ == 101) {
            return gpsBuilder_.getMessage();
          }
          return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage.getDefaultInstance();
        }
      }
      /**
       * <code>optional .mymqttmessages.GPSMessage gps = 101;</code>
       */
      public Builder setGps(com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage value) {
        if (gpsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msgtype_ = value;
          onChanged();
        } else {
          gpsBuilder_.setMessage(value);
        }
        msgtypeCase_ = 101;
        return this;
      }
      /**
       * <code>optional .mymqttmessages.GPSMessage gps = 101;</code>
       */
      public Builder setGps(
          com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage.Builder builderForValue) {
        if (gpsBuilder_ == null) {
          msgtype_ = builderForValue.build();
          onChanged();
        } else {
          gpsBuilder_.setMessage(builderForValue.build());
        }
        msgtypeCase_ = 101;
        return this;
      }
      /**
       * <code>optional .mymqttmessages.GPSMessage gps = 101;</code>
       */
      public Builder mergeGps(com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage value) {
        if (gpsBuilder_ == null) {
          if (msgtypeCase_ == 101 &&
              msgtype_ != com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage.getDefaultInstance()) {
            msgtype_ = com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage.newBuilder((com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage) msgtype_)
                .mergeFrom(value).buildPartial();
          } else {
            msgtype_ = value;
          }
          onChanged();
        } else {
          if (msgtypeCase_ == 101) {
            gpsBuilder_.mergeFrom(value);
          }
          gpsBuilder_.setMessage(value);
        }
        msgtypeCase_ = 101;
        return this;
      }
      /**
       * <code>optional .mymqttmessages.GPSMessage gps = 101;</code>
       */
      public Builder clearGps() {
        if (gpsBuilder_ == null) {
          if (msgtypeCase_ == 101) {
            msgtypeCase_ = 0;
            msgtype_ = null;
            onChanged();
          }
        } else {
          if (msgtypeCase_ == 101) {
            msgtypeCase_ = 0;
            msgtype_ = null;
          }
          gpsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .mymqttmessages.GPSMessage gps = 101;</code>
       */
      public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage.Builder getGpsBuilder() {
        return getGpsFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .mymqttmessages.GPSMessage gps = 101;</code>
       */
      public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessageOrBuilder getGpsOrBuilder() {
        if ((msgtypeCase_ == 101) && (gpsBuilder_ != null)) {
          return gpsBuilder_.getMessageOrBuilder();
        } else {
          if (msgtypeCase_ == 101) {
            return (com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage) msgtype_;
          }
          return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage.getDefaultInstance();
        }
      }
      /**
       * <code>optional .mymqttmessages.GPSMessage gps = 101;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage, com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage.Builder, com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessageOrBuilder> 
          getGpsFieldBuilder() {
        if (gpsBuilder_ == null) {
          if (!(msgtypeCase_ == 101)) {
            msgtype_ = com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage.getDefaultInstance();
          }
          gpsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage, com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage.Builder, com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessageOrBuilder>(
                  (com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage) msgtype_,
                  getParentForChildren(),
                  isClean());
          msgtype_ = null;
        }
        msgtypeCase_ = 101;
        onChanged();
        return gpsBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues, com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues.Builder, com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValuesOrBuilder> metaBuilder_;
      /**
       * <code>optional .mymqttmessages.MetaValues meta = 102;</code>
       */
      public boolean hasMeta() {
        return msgtypeCase_ == 102;
      }
      /**
       * <code>optional .mymqttmessages.MetaValues meta = 102;</code>
       */
      public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues getMeta() {
        if (metaBuilder_ == null) {
          if (msgtypeCase_ == 102) {
            return (com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues) msgtype_;
          }
          return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues.getDefaultInstance();
        } else {
          if (msgtypeCase_ == 102) {
            return metaBuilder_.getMessage();
          }
          return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues.getDefaultInstance();
        }
      }
      /**
       * <code>optional .mymqttmessages.MetaValues meta = 102;</code>
       */
      public Builder setMeta(com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues value) {
        if (metaBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          msgtype_ = value;
          onChanged();
        } else {
          metaBuilder_.setMessage(value);
        }
        msgtypeCase_ = 102;
        return this;
      }
      /**
       * <code>optional .mymqttmessages.MetaValues meta = 102;</code>
       */
      public Builder setMeta(
          com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues.Builder builderForValue) {
        if (metaBuilder_ == null) {
          msgtype_ = builderForValue.build();
          onChanged();
        } else {
          metaBuilder_.setMessage(builderForValue.build());
        }
        msgtypeCase_ = 102;
        return this;
      }
      /**
       * <code>optional .mymqttmessages.MetaValues meta = 102;</code>
       */
      public Builder mergeMeta(com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues value) {
        if (metaBuilder_ == null) {
          if (msgtypeCase_ == 102 &&
              msgtype_ != com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues.getDefaultInstance()) {
            msgtype_ = com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues.newBuilder((com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues) msgtype_)
                .mergeFrom(value).buildPartial();
          } else {
            msgtype_ = value;
          }
          onChanged();
        } else {
          if (msgtypeCase_ == 102) {
            metaBuilder_.mergeFrom(value);
          }
          metaBuilder_.setMessage(value);
        }
        msgtypeCase_ = 102;
        return this;
      }
      /**
       * <code>optional .mymqttmessages.MetaValues meta = 102;</code>
       */
      public Builder clearMeta() {
        if (metaBuilder_ == null) {
          if (msgtypeCase_ == 102) {
            msgtypeCase_ = 0;
            msgtype_ = null;
            onChanged();
          }
        } else {
          if (msgtypeCase_ == 102) {
            msgtypeCase_ = 0;
            msgtype_ = null;
          }
          metaBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>optional .mymqttmessages.MetaValues meta = 102;</code>
       */
      public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues.Builder getMetaBuilder() {
        return getMetaFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .mymqttmessages.MetaValues meta = 102;</code>
       */
      public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValuesOrBuilder getMetaOrBuilder() {
        if ((msgtypeCase_ == 102) && (metaBuilder_ != null)) {
          return metaBuilder_.getMessageOrBuilder();
        } else {
          if (msgtypeCase_ == 102) {
            return (com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues) msgtype_;
          }
          return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues.getDefaultInstance();
        }
      }
      /**
       * <code>optional .mymqttmessages.MetaValues meta = 102;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues, com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues.Builder, com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValuesOrBuilder> 
          getMetaFieldBuilder() {
        if (metaBuilder_ == null) {
          if (!(msgtypeCase_ == 102)) {
            msgtype_ = com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues.getDefaultInstance();
          }
          metaBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues, com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues.Builder, com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValuesOrBuilder>(
                  (com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues) msgtype_,
                  getParentForChildren(),
                  isClean());
          msgtype_ = null;
        }
        msgtypeCase_ = 102;
        onChanged();
        return metaBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mymqttmessages.PathItemMessage)
    }

    // @@protoc_insertion_point(class_scope:mymqttmessages.PathItemMessage)
    private static final com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage();
    }

    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    public static final com.google.protobuf.Parser<PathItemMessage>
        PARSER = new com.google.protobuf.AbstractParser<PathItemMessage>() {
      public PathItemMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new PathItemMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PathItemMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PathItemMessage> getParserForType() {
      return PARSER;
    }

    public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.PathItemMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MetaValuesOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mymqttmessages.MetaValues)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required uint64 time = 1;</code>
     */
    boolean hasTime();
    /**
     * <code>required uint64 time = 1;</code>
     */
    long getTime();

    /**
     * <code>required double distance = 2;</code>
     */
    boolean hasDistance();
    /**
     * <code>required double distance = 2;</code>
     */
    double getDistance();

    /**
     * <code>required double speed = 3;</code>
     */
    boolean hasSpeed();
    /**
     * <code>required double speed = 3;</code>
     */
    double getSpeed();

    /**
     * <code>required uint32 steps = 4;</code>
     */
    boolean hasSteps();
    /**
     * <code>required uint32 steps = 4;</code>
     */
    int getSteps();
  }
  /**
   * Protobuf type {@code mymqttmessages.MetaValues}
   */
  public  static final class MetaValues extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mymqttmessages.MetaValues)
      MetaValuesOrBuilder {
    // Use MetaValues.newBuilder() to construct.
    private MetaValues(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MetaValues() {
      time_ = 0L;
      distance_ = 0D;
      speed_ = 0D;
      steps_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MetaValues(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              time_ = input.readUInt64();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              distance_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              speed_ = input.readDouble();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              steps_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_MetaValues_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_MetaValues_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues.class, com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues.Builder.class);
    }

    private int bitField0_;
    public static final int TIME_FIELD_NUMBER = 1;
    private long time_;
    /**
     * <code>required uint64 time = 1;</code>
     */
    public boolean hasTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 time = 1;</code>
     */
    public long getTime() {
      return time_;
    }

    public static final int DISTANCE_FIELD_NUMBER = 2;
    private double distance_;
    /**
     * <code>required double distance = 2;</code>
     */
    public boolean hasDistance() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double distance = 2;</code>
     */
    public double getDistance() {
      return distance_;
    }

    public static final int SPEED_FIELD_NUMBER = 3;
    private double speed_;
    /**
     * <code>required double speed = 3;</code>
     */
    public boolean hasSpeed() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required double speed = 3;</code>
     */
    public double getSpeed() {
      return speed_;
    }

    public static final int STEPS_FIELD_NUMBER = 4;
    private int steps_;
    /**
     * <code>required uint32 steps = 4;</code>
     */
    public boolean hasSteps() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required uint32 steps = 4;</code>
     */
    public int getSteps() {
      return steps_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTime()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDistance()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSpeed()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSteps()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, time_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, distance_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeDouble(3, speed_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, steps_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, time_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, distance_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, speed_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, steps_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues)) {
        return super.equals(obj);
      }
      com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues other = (com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues) obj;

      boolean result = true;
      result = result && (hasTime() == other.hasTime());
      if (hasTime()) {
        result = result && (getTime()
            == other.getTime());
      }
      result = result && (hasDistance() == other.hasDistance());
      if (hasDistance()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getDistance())
            == java.lang.Double.doubleToLongBits(
                other.getDistance()));
      }
      result = result && (hasSpeed() == other.hasSpeed());
      if (hasSpeed()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getSpeed())
            == java.lang.Double.doubleToLongBits(
                other.getSpeed()));
      }
      result = result && (hasSteps() == other.hasSteps());
      if (hasSteps()) {
        result = result && (getSteps()
            == other.getSteps());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTime()) {
        hash = (37 * hash) + TIME_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTime());
      }
      if (hasDistance()) {
        hash = (37 * hash) + DISTANCE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getDistance()));
      }
      if (hasSpeed()) {
        hash = (37 * hash) + SPEED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getSpeed()));
      }
      if (hasSteps()) {
        hash = (37 * hash) + STEPS_FIELD_NUMBER;
        hash = (53 * hash) + getSteps();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data.array());
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data.array(), extensionRegistry);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mymqttmessages.MetaValues}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mymqttmessages.MetaValues)
        com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValuesOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_MetaValues_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_MetaValues_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues.class, com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues.Builder.class);
      }

      // Construct using com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        time_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        distance_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        speed_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        steps_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_MetaValues_descriptor;
      }

      public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues getDefaultInstanceForType() {
        return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues.getDefaultInstance();
      }

      public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues build() {
        com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues buildPartial() {
        com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues result = new com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.time_ = time_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.distance_ = distance_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.speed_ = speed_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.steps_ = steps_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues) {
          return mergeFrom((com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues other) {
        if (other == com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues.getDefaultInstance()) return this;
        if (other.hasTime()) {
          setTime(other.getTime());
        }
        if (other.hasDistance()) {
          setDistance(other.getDistance());
        }
        if (other.hasSpeed()) {
          setSpeed(other.getSpeed());
        }
        if (other.hasSteps()) {
          setSteps(other.getSteps());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTime()) {
          return false;
        }
        if (!hasDistance()) {
          return false;
        }
        if (!hasSpeed()) {
          return false;
        }
        return hasSteps();
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long time_ ;
      /**
       * <code>required uint64 time = 1;</code>
       */
      public boolean hasTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required uint64 time = 1;</code>
       */
      public long getTime() {
        return time_;
      }
      /**
       * <code>required uint64 time = 1;</code>
       */
      public Builder setTime(long value) {
        bitField0_ |= 0x00000001;
        time_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint64 time = 1;</code>
       */
      public Builder clearTime() {
        bitField0_ = (bitField0_ & ~0x00000001);
        time_ = 0L;
        onChanged();
        return this;
      }

      private double distance_ ;
      /**
       * <code>required double distance = 2;</code>
       */
      public boolean hasDistance() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double distance = 2;</code>
       */
      public double getDistance() {
        return distance_;
      }
      /**
       * <code>required double distance = 2;</code>
       */
      public Builder setDistance(double value) {
        bitField0_ |= 0x00000002;
        distance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double distance = 2;</code>
       */
      public Builder clearDistance() {
        bitField0_ = (bitField0_ & ~0x00000002);
        distance_ = 0D;
        onChanged();
        return this;
      }

      private double speed_ ;
      /**
       * <code>required double speed = 3;</code>
       */
      public boolean hasSpeed() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required double speed = 3;</code>
       */
      public double getSpeed() {
        return speed_;
      }
      /**
       * <code>required double speed = 3;</code>
       */
      public Builder setSpeed(double value) {
        bitField0_ |= 0x00000004;
        speed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double speed = 3;</code>
       */
      public Builder clearSpeed() {
        bitField0_ = (bitField0_ & ~0x00000004);
        speed_ = 0D;
        onChanged();
        return this;
      }

      private int steps_ ;
      /**
       * <code>required uint32 steps = 4;</code>
       */
      public boolean hasSteps() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required uint32 steps = 4;</code>
       */
      public int getSteps() {
        return steps_;
      }
      /**
       * <code>required uint32 steps = 4;</code>
       */
      public Builder setSteps(int value) {
        bitField0_ |= 0x00000008;
        steps_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 steps = 4;</code>
       */
      public Builder clearSteps() {
        bitField0_ = (bitField0_ & ~0x00000008);
        steps_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mymqttmessages.MetaValues)
    }

    // @@protoc_insertion_point(class_scope:mymqttmessages.MetaValues)
    private static final com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues();
    }

    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

   public static final com.google.protobuf.Parser<MetaValues>
        PARSER = new com.google.protobuf.AbstractParser<MetaValues>() {
      public MetaValues parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new MetaValues(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MetaValues> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MetaValues> getParserForType() {
      return PARSER;
    }

    public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.MetaValues getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GPSMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:mymqttmessages.GPSMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required double latitude = 1;</code>
     */
    boolean hasLatitude();
    /**
     * <code>required double latitude = 1;</code>
     */
    double getLatitude();

    /**
     * <code>required double longitude = 2;</code>
     */
    boolean hasLongitude();
    /**
     * <code>required double longitude = 2;</code>
     */
    double getLongitude();
  }
  /**
   * Protobuf type {@code mymqttmessages.GPSMessage}
   */
  public  static final class GPSMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:mymqttmessages.GPSMessage)
      GPSMessageOrBuilder {
    // Use GPSMessage.newBuilder() to construct.
    private GPSMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GPSMessage() {
      latitude_ = 0D;
      longitude_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GPSMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              latitude_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              longitude_ = input.readDouble();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_GPSMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_GPSMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage.class, com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage.Builder.class);
    }

    private int bitField0_;
    public static final int LATITUDE_FIELD_NUMBER = 1;
    private double latitude_;
    /**
     * <code>required double latitude = 1;</code>
     */
    public boolean hasLatitude() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required double latitude = 1;</code>
     */
    public double getLatitude() {
      return latitude_;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 2;
    private double longitude_;
    /**
     * <code>required double longitude = 2;</code>
     */
    public boolean hasLongitude() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double longitude = 2;</code>
     */
    public double getLongitude() {
      return longitude_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasLatitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLongitude()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, latitude_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, longitude_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, latitude_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, longitude_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage)) {
        return super.equals(obj);
      }
      com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage other = (com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage) obj;

      boolean result = true;
      result = result && (hasLatitude() == other.hasLatitude());
      if (hasLatitude()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getLatitude())
            == java.lang.Double.doubleToLongBits(
                other.getLatitude()));
      }
      result = result && (hasLongitude() == other.hasLongitude());
      if (hasLongitude()) {
        result = result && (
            java.lang.Double.doubleToLongBits(getLongitude())
            == java.lang.Double.doubleToLongBits(
                other.getLongitude()));
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasLatitude()) {
        hash = (37 * hash) + LATITUDE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getLatitude()));
      }
      if (hasLongitude()) {
        hash = (37 * hash) + LONGITUDE_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getLongitude()));
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data.array());
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data.array(), extensionRegistry);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code mymqttmessages.GPSMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:mymqttmessages.GPSMessage)
        com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_GPSMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_GPSMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage.class, com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage.Builder.class);
      }

      // Construct using com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        latitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        longitude_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.internal_static_mymqttmessages_GPSMessage_descriptor;
      }

      public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage getDefaultInstanceForType() {
        return com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage.getDefaultInstance();
      }

      public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage build() {
        com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage buildPartial() {
        com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage result = new com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.latitude_ = latitude_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.longitude_ = longitude_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage) {
          return mergeFrom((com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage other) {
        if (other == com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage.getDefaultInstance()) return this;
        if (other.hasLatitude()) {
          setLatitude(other.getLatitude());
        }
        if (other.hasLongitude()) {
          setLongitude(other.getLongitude());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasLatitude()) {
          return false;
        }
        return hasLongitude();
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private double latitude_ ;
      /**
       * <code>required double latitude = 1;</code>
       */
      public boolean hasLatitude() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required double latitude = 1;</code>
       */
      public double getLatitude() {
        return latitude_;
      }
      /**
       * <code>required double latitude = 1;</code>
       */
      public Builder setLatitude(double value) {
        bitField0_ |= 0x00000001;
        latitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double latitude = 1;</code>
       */
      public Builder clearLatitude() {
        bitField0_ = (bitField0_ & ~0x00000001);
        latitude_ = 0D;
        onChanged();
        return this;
      }

      private double longitude_ ;
      /**
       * <code>required double longitude = 2;</code>
       */
      public boolean hasLongitude() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double longitude = 2;</code>
       */
      public double getLongitude() {
        return longitude_;
      }
      /**
       * <code>required double longitude = 2;</code>
       */
      public Builder setLongitude(double value) {
        bitField0_ |= 0x00000002;
        longitude_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double longitude = 2;</code>
       */
      public Builder clearLongitude() {
        bitField0_ = (bitField0_ & ~0x00000002);
        longitude_ = 0D;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:mymqttmessages.GPSMessage)
    }

    // @@protoc_insertion_point(class_scope:mymqttmessages.GPSMessage)
    private static final com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage();
    }

    public static com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

      public static final com.google.protobuf.Parser<GPSMessage>
        PARSER = new com.google.protobuf.AbstractParser<GPSMessage>() {
      public GPSMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GPSMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GPSMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GPSMessage> getParserForType() {
      return PARSER;
    }

    public com.example.harald.runwithme2.mymqttmessages.ProtobufMessages.GPSMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mymqttmessages_PathItemMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mymqttmessages_PathItemMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mymqttmessages_MetaValues_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mymqttmessages_MetaValues_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mymqttmessages_GPSMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mymqttmessages_GPSMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024mymqttmessages.proto\022\016mymqttmessages\"\203" +
      "\001\n\017PathItemMessage\022\016\n\006source\030\001 \002(\r\022)\n\003gp" +
      "s\030e \001(\0132\032.mymqttmessages.GPSMessageH\000\022*\n" +
      "\004meta\030f \001(\0132\032.mymqttmessages.MetaValuesH" +
      "\000B\t\n\007msgtype\"J\n\nMetaValues\022\014\n\004time\030\001 \002(\004" +
      "\022\020\n\010distance\030\002 \002(\001\022\r\n\005speed\030\003 \002(\001\022\r\n\005ste" +
      "ps\030\004 \002(\r\"1\n\nGPSMessage\022\020\n\010latitude\030\001 \002(\001" +
      "\022\021\n\tlongitude\030\002 \002(\001B@\n,com.example.haral" +
      "d.runwithme2.mymqttmessagesB\020ProtobufMes" +
      "sages"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_mymqttmessages_PathItemMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mymqttmessages_PathItemMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mymqttmessages_PathItemMessage_descriptor,
        new java.lang.String[] { "Source", "Gps", "Meta", "Msgtype", });
    internal_static_mymqttmessages_MetaValues_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mymqttmessages_MetaValues_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mymqttmessages_MetaValues_descriptor,
        new java.lang.String[] { "Time", "Distance", "Speed", "Steps", });
    internal_static_mymqttmessages_GPSMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_mymqttmessages_GPSMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mymqttmessages_GPSMessage_descriptor,
        new java.lang.String[] { "Latitude", "Longitude", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
